title: Abra White | Portfolio
description: Some examples of past work acrosss languages, etc.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

github-username: awhite2

gems:
  - jekyll-mentions
